version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: lrdstest-memcached
      networks:
        - default-network

    mariadb:
      image: mariadb:10.4
      container_name: lrdstest-mysql
      working_dir: /application
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=lrdstest
        - MYSQL_USER=lrdstest
        - MYSQL_PASSWORD=secret
      ports:
        - "8992:3306"
      networks:
        - default-network

    webserver:
      image: nginx:alpine
      container_name: lrdstest-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8890:80"
      networks:
        - default-network

    php-fpm:
      build: ./
      container_name: lrdstest-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        - default-network

networks:
  default-network:
    driver: bridge
